spring:
  application:
    name: springboot-backend
  datasource:
    url: jdbc:mysql://localhost:3306/auth_boilerplate
    username: root
    password: nam123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true




app:
  secure:
    jwt:
      secretKey: MHQCAQEEIEYgBlyQVsH7SpHUH7x4RErcckhu7ary/JjhP72Nk19EoAcGBSuBBAAKoUQDQgAE1MtHIxlGP5TARqBccrddNm1FnYH1Fp+onETz5KbXPSeG5FGwKMUXGfAmSZJq2gENULFewwymt+9bTXkjBZhh8A==
      tokenExpireTime: 60000
      refreshTokenExpireTime: 10080000

ignored:
  - /api/v1/auth
  - /api/v1/register
