spring:
  application:
    name: springboot-backend
  datasource:
    url: jdbc:mysql://localhost:3300/tech_shop
    username: root
    password: nemisolv
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nemisolv
    password: kqtgsvxoqyonuiny
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 108748481333-q03ovpcihsp67ngr7d3apam9feolosgv.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 1106813467180481
            clientSecret: 7ffa2355ccf06f28aee9c121909e45c7
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: Iv23ligkDN0nZfgoi5HE
            clientSecret: 1dcce0ff2e60c015efe37a61b6cd7bd3835a62bb
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
#          provider:
#            facebook:
#              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
#              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
#              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,picture






app:
  secure:
    jwt:
      secretKey: MHQCAQEEIEYgBlyQVsH7SpHUH7x4RErcckhu7ary/JjhP72Nk19EoAcGBSuBBAAKoUQDQgAE1MtHIxlGP5TARqBccrddNm1FnYH1Fp+onETz5KbXPSeG5FGwKMUXGfAmSZJq2gENULFewwymt+9bTXkjBZhh8A==
      tokenExpireTime: 6000000000
      refreshTokenExpireTime: 100800000000
  mail:
    from: nemisolv@gmail.com
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

  ignored:
    urls:
      - /api/v1/auth/**

